os:
- linux
language: node_js
node_js:
- '7'
- '6'
branches:
  only:
    - master
cache: yarn
env:
  - SUB_DIR=client
  - SUB_DIR=server
before_install:
  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_key -in travis.tar.enc -out travis.tar -d
  - tar xvf travis.tar
install:
- yarn global add @angular/cli
- cd $SUB_DIR
- yarn install
script:
- yarn run autotest
