jobs:
    include:
        - stage: client
          language: node_js
          node_js: '12'
          before_install: cd client

        - stage: server
          language: node_js
          node_js: '12'
          before_install: cd server

        - stage: deploy
          script: skip
          deploy:
              - provider: script
                script: bash deploy.sh Evie_BuildDev $API_TOKEN
                on:
                    branch: master
                    repo: Ionaru/EVIE
              - provider: script
                script: bash deploy.sh Evie_BuildProd $API_TOKEN
                on:
                    branch: master
                    tags: true
                    repo: Ionaru/EVIE

env:
    global:
        - secure: Z6syCWWlUuzXFqdTZM3hDtoIyY6aISLqiQd5USiq2vbhMgWu1KVGjGwlbfBKeKFUdJGMvAEF34nDSRc9KF40fn+tv75YektKn6lTXjUrvYE3JhUPDH9EKPI68Pgxt+uy1wEs8UCZamIEhw+nY4+V5YG/DROhv8bNaMKZZesNgctcpg+sO71lD/HX0cRg/YviIWTP6KtHNha4BhhGgYxEITfy8A7GiwAq34u3c8GIwblCTiegWzqcuAs20z9zsbjanaA3vi3xtoGKAXDJh/AIxxo6zcgR3xziWiVF256WXn7cJwdRmQnozBZUwUwvW3TC/5MdJMubsgo3oyFN/xkYKKFiIn5A+KXbW1ZmNuBu4xeJqlYisgFjdpLjKk6vT8OalI6h+gHPX2on7+CqjI+90DrfX6uY77SaOeWNrPtOEzXvFu2z0eh0ifla84o38y22Ybv/0cZEooc7Oq/Hxl5hGWR1clWQ1Q22zg4SQyq2QWYSTLQoXRYcurIVTXhMf6c99Q7rzZns98a6aCdHwxncH48evwDJ06CMKql0hagy4TCRIPxEQ2rOlHMZ2LAmgFPDFXSEtvL2i78vIGUP4pFMdJncaUd3ePc9r1MeP2zYW6VnZvpSPHKU3PddGcZjLLAFvUMp8HQ9/qvEkogbyxk+uOcPPCLPICxamgyHOKJSrW0=
        - secure: BqaZRaciWFW0aiE+G+vsWmTjqUlKi2Wt2wUjFnP6pF/51nWu7s00n+Ue9c6Hl3z7ghe8YuLO+WSjZFm2A69S+EkAI0H4GYPYMr8CpWamgLMiWiLpUAyjRF4/74asYa8mobZBYr2NARK2WDHTgIwzgK/JJaVopEGRykK9/XNo5DVvytA786X5u7X6YSLPETCJjbXAFCAHMI7MPWePeclLdNZix8291/ibA9TsRn4u1Tlwf+H1OfCJDZo8DCd4iRauEjEcHMJ0+Fb5+O7oxaZ9/mhQ3CzB0SHV+njAkygd1Ird5O2VsAVfMvNAOnhprmOWbcOl9JSiTYDMx+JkDxZ8KWVDgzQHpRrJmwMPnbr8v1CiAzH/qiBwTlRerRFE+rFSFabp5HNv1fNfKC6pIkKSiwHmnUhbqIZRD0WD3pvPMxM8cHdBL8OCvPAC18rfZnwEHG74xG3ynXREdosYmRAOCHdq/gVnfRsiTGMnCTefYvnj/W3kx1kFoU80lrGYojbbQHQ34hICyjOO8JMYYEhaHn8DjrCAArp2j85WbJaWnFOsjeb10z+n5LYsnQt08hg/wNgNyFkZKP7ToFcymmeGDJHbFNXsdUJqn2+wTAnwiVHRP7rSHDQEacHpGJH8fB3sHNyExIpuskNT/g3vyv0r0k9XIHQtlW7wqG/nacYUI3c=
