os:
- linux
language: node_js
node_js:
- '7'
- '6'
- '5'
- '4'
env:
  - SUB_DIR=client
  - SUB_DIR=server
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
- cd $SUB_DIR
- yarn install
script:
- yarn run "lint"
cache:
  directories:
  - $HOME/.cache/yarn
