os:
- linux
language: node_js
node_js:
- '7'
- '6'
branches:
  only:
  - master
cache: yarn
env:
- SUB_DIR=client
- SUB_DIR=server
install:
- sudo yarn global add @angular/cli
- tar xvf travis.tar
- cd $SUB_DIR
- yarn install
script:
- yarn run autotest
dd:
- openssl aes-256-cbc -K $encrypted_170d92a4e5a8_key -iv $encrypted_170d92a4e5a8_iv
  -in travis.tar.enc -out travis.tar -d
sudo: required
