os:
- linux
language: node_js
node_js:
- '8'
branches:
  only:
  - master
env:
- SUB_DIR=client
- SUB_DIR=server
addons:
  code_climate:
    repo_token: 991fdd0a58ec462128731b217a70ea9e1d48811185765b21f10a59c3da1ffb6f
before_install:
- openssl aes-256-cbc -K $encrypted_170d92a4e5a8_key -iv $encrypted_170d92a4e5a8_iv
  -in travis.tar.enc -out travis.tar -d
install:
- if [[ "$SUB_DIR" == "client" ]]; then npm install -g @angular/cli; fi
- if [[ "$SUB_DIR" == "client" ]]; then npm install -g codeclimate-test-reporter; fi
- tar xvf travis.tar
- cd $SUB_DIR
- npm install
script:
- npm run autotest
after_script:
- if [[ "$SUB_DIR" == "client" ]]; then codeclimate-test-reporter < ./coverage/lcov.info; fi
