version: '3'
services:
    evie-client:
        container_name: evie-client
        build:
            context: ./
            dockerfile: ./client/Dockerfile
            args:
                FA_TOKEN: ${FA_TOKEN}
        ports:
            - "8080:80"
        depends_on:
            - evie-server
    evie-server:
        container_name: evie-server
        build:
            context: ./
            dockerfile: ./server/Dockerfile
        ports:
            - "3000:3000"
