version: '3'
services:
    client:
        container_name: evie-client
        build:
            context: ./
            dockerfile: ./client/Dockerfile
            args:
                FA_TOKEN: ${FA_TOKEN}
        ports:
            - "80:80"
