version: '3'
services:

    client:
        build:
            context: ./client
            args:
                - EVIE_FA_TOKEN
                - EVIE_ENV
        restart: unless-stopped
        ports:
            - "${EVIE_CLIENT_PORT:-80}:80"
        depends_on:
            - server

    server:
        build: ./server
        environment:
            - DEBUG
            - EVIE_DB_NAME
            - EVIE_DB_HOST
            - EVIE_DB_PORT
            - EVIE_DB_USER
            - EVIE_DB_PASS
            - EVIE_DB_SSL_CA
            - EVIE_DB_SSL_CERT
            - EVIE_DB_SSL_KEY
            - EVIE_DB_SSL_REJECT
            - EVIE_CONFIG_VOLUME
        ports:
            - "${EVIE_SERVER_PORT:-3731}"
        restart: unless-stopped
        volumes:
            - ${EVIE_CONFIG_VOLUME:-config-volume}:/app/config
            - ${EVIE_DATA_VOLUME:-data-volume}:/app/data
            - ${EVIE_LOG_VOLUME:-log-volume}:/app/logs

volumes:
    config-volume:
    data-volume:
    log-volume:
