version: '3'
services:

    evie-client:
        build:
            context: ./client
            args:
                FA_TOKEN: ${FA_TOKEN}
        container_name: evie-client
        env_file:
            - .env
        ports:
            - "${CLIENT_PORT}:80"
        depends_on:
            - evie-server

    evie-server:
        build: ./server
        container_name: evie-server
        env_file:
            - .env
        ports:
            - "${SERVER_PORT}:3000"
