name: EVIE CD

on:
    push:
        branches:
            - master
        tags:
            - '*'
    pull_request:
        branches:
            - master

jobs:
    client-test:

        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'

            - name: Audit
              working-directory: client
              env:
                  EVIE_FA_TOKEN: ${{ secrets.FA_TOKEN }}
              run: npm audit

            - name: Install packages
              working-directory: client
              env:
                  EVIE_FA_TOKEN: ${{ secrets.FA_TOKEN }}
              run: npm install

            - name: Run tests
              working-directory: client
              env:
                  EVIE_FA_TOKEN: ${{ secrets.FA_TOKEN }}
              run: npm test

    server-test:

        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'

            - name: Audit
              working-directory: server
              run: npm audit

            - name: Install packages
              working-directory: server
              run: npm install

            - name: Run tests
              working-directory: server
              run: npm test

    deploy:

        needs: [client-test, server-test]
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'

            - name: Deploy to dev.spaceships.app
              if: startsWith(github.ref, 'refs/heads/')
              run: npx -q @ionaru/teamcity-deploy teamcity.saturnserver.org Evie_BuildDev ${{ secrets.API_TOKEN }}

            - name: Deploy to spaceships.app
              if: startsWith(github.ref, 'refs/tags/')
              run: npx -q @ionaru/teamcity-deploy teamcity.saturnserver.org Evie_BuildProd ${{ secrets.API_TOKEN }}
